name: 'weather_dbt'
version: '1.0'
config-version: 2
profile: 'weather_dbt'

model-paths: ['models']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
test-paths: ['tests']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  weather_dbt:
    +materialized: view
    staging:
      +schema: staging
    core:
      +schema: staging
    marts:
      +schema: marts