weather_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: weather
      schema: public
      threads: 4
      connect_timeout: 10
